package com.starception.submission.feature.quran

/**
 * Data class representing a Surah (chapter) of the Quran
 */
data class Surah(
    val number: Int,
    val nameArabic: String,
    val nameEnglish: String,
    val fileName: String,
    val revelationType: String, // "Meccan" or "Medinan"
    val fileNameBengali: String = "" // Default empty, will be found dynamically
)

enum class AudioLanguage {
    ARABIC_ONLY,
    BENGALI_TRANSLATION,
    ENGLISH_TRANSLATION
}

/**
 * Complete list of all 114 Surahs with their information
 */
object QuranData {
    val surahs = listOf(
        Surah(1, "ٱلْفَاتِحَة", "Al-Fatihah", "001-al-fatihah.ogg", "Meccan", "001 - Al-Fatihah ( The Opening ) - سورة الفاتحة.ogg"),
        Surah(2, "ٱلْبَقَرَة", "Al-Baqarah", "002-al-baqarah.ogg", "Medinan", "002 - Al-Baqarah ( The Cow ) - سورة البقرة.ogg"),
        Surah(3, "آلِ عِمْرَان", "Al-Imran", "003-al-imran.ogg", "Medinan", "003 - Al-Imran ( The Family of Imran ) - سورة آل عمران.ogg"),
        Surah(4, "ٱلنِّسَاء", "An-Nisa", "004-an-nisa.ogg", "Medinan", "004 - An-Nisa ( The Women ) - سورة النساء.ogg"),
        Surah(5, "ٱلْمَائِدَة", "Al-Maidah", "005-al-maidah.ogg", "Medinan", "005 - Al-Maidah ( The Table spread with Food ) - سورة المائدة.ogg"),
        Surah(6, "ٱلْأَنْعَام", "Al-Anam", "006-al-anam.ogg", "Meccan", "006 - Al-An'am ( The Cattle ) - سورة الأنعام.ogg"),
        Surah(7, "ٱلْأَعْرَاف", "Al-Araf", "007-al-araf.ogg", "Meccan"),
        Surah(8, "ٱلْأَنفَال", "Al-Anfal", "008-al-anfal.ogg", "Medinan"),
        Surah(9, "ٱلتَّوْبَة", "At-Taubah", "009-at-taubah.ogg", "Medinan"),
        Surah(10, "يُونُس", "Yunus", "010-yunus.ogg", "Meccan"),
        Surah(11, "هُود", "Hud", "011-hud.ogg", "Meccan"),
        Surah(12, "يُوسُف", "Yusuf", "012-yusuf.ogg", "Meccan"),
        Surah(13, "ٱلرَّعْد", "Ar-Rad", "013-ar-rad.ogg", "Medinan"),
        Surah(14, "إِبْرَاهِيم", "Ibrahim", "014-ibrahim.ogg", "Meccan"),
        Surah(15, "ٱلْحِجْر", "Al-Hijr", "015-al-hijr.ogg", "Meccan"),
        Surah(16, "ٱلنَّحْل", "An-Nahl", "016-an-nahl.ogg", "Meccan"),
        Surah(17, "ٱلْإِسْرَاء", "Al-Isra", "017-al-isra.ogg", "Meccan"),
        Surah(18, "ٱلْكَهْف", "Al-Kahf", "018-al-kahf.ogg", "Meccan"),
        Surah(19, "مَرْيَم", "Maryam", "019-maryam.ogg", "Meccan"),
        Surah(20, "طه", "Ta-Ha", "020-ta-ha.ogg", "Meccan"),
        Surah(21, "ٱلْأَنبِيَاء", "Al-Anbiya", "021-al-anbiya.ogg", "Meccan"),
        Surah(22, "ٱلْحَجّ", "Al-Hajj", "022-al-hajj.ogg", "Medinan"),
        Surah(23, "ٱلْمُؤْمِنُون", "Al-Muminun", "023-al-muminun.ogg", "Meccan"),
        Surah(24, "ٱلنُّور", "An-Nur", "024-an-nur.ogg", "Medinan"),
        Surah(25, "ٱلْفُرْقَان", "Al-Furqan", "025-al-furqan.ogg", "Meccan"),
        Surah(26, "ٱلشُّعَرَاء", "Ash-Shuara", "026-ash-shuara.ogg", "Meccan"),
        Surah(27, "ٱلنَّمْل", "An-Naml", "027-an-naml.ogg", "Meccan"),
        Surah(28, "ٱلْقَصَص", "Al-Qasas", "028-al-qasas.ogg", "Meccan"),
        Surah(29, "ٱلْعَنكَبُوت", "Al-Ankabut", "029-al-ankabut.ogg", "Meccan"),
        Surah(30, "ٱلرُّوم", "Ar-Rum", "030-ar-rum.ogg", "Meccan"),
        Surah(31, "لُقْمَان", "Luqman", "031-luqman.ogg", "Meccan"),
        Surah(32, "ٱلسَّجْدَة", "As-Sajdah", "032-as-sajdah.ogg", "Meccan"),
        Surah(33, "ٱلْأَحْزَاب", "Al-Ahzab", "033-al-ahzab.ogg", "Medinan"),
        Surah(34, "سَبَإ", "Saba", "034-saba.ogg", "Meccan"),
        Surah(35, "فَاطِر", "Fatir", "035-fatir.ogg", "Meccan"),
        Surah(36, "يس", "Ya-Sin", "036-ya-sin.ogg", "Meccan"),
        Surah(37, "ٱلصَّافَّات", "As-Saffat", "037-as-saffat.ogg", "Meccan"),
        Surah(38, "ص", "Sad", "038-sad.ogg", "Meccan"),
        Surah(39, "ٱلزُّمَر", "Az-Zumar", "039-az-zumar.ogg", "Meccan"),
        Surah(40, "غَافِر", "Ghafir", "040-ghafir.ogg", "Meccan"),
        Surah(41, "فُصِّلَت", "Fussilat", "041-fussilat.ogg", "Meccan"),
        Surah(42, "ٱلشُّورَىٰ", "Ash-Shura", "042-ash-shura.ogg", "Meccan"),
        Surah(43, "ٱلزُّخْرُف", "Az-Zukhruf", "043-az-zukhruf.ogg", "Meccan"),
        Surah(44, "ٱلدُّخَان", "Ad-Dukhan", "044-ad-dukhan.ogg", "Meccan"),
        Surah(45, "ٱلْجَاثِيَة", "Al-Jathiyah", "045-al-jathiyah.ogg", "Meccan"),
        Surah(46, "ٱلْأَحْقَاف", "Al-Ahqaf", "046-al-ahqaf.ogg", "Meccan"),
        Surah(47, "مُحَمَّد", "Muhammad", "047-muhammad.ogg", "Medinan"),
        Surah(48, "ٱلْفَتْح", "Al-Fath", "048-al-fath.ogg", "Medinan"),
        Surah(49, "ٱلْحُجُرَات", "Al-Hujurat", "049-al-hujurat.ogg", "Medinan"),
        Surah(50, "ق", "Qaf", "050-qaf.ogg", "Meccan"),
        Surah(51, "ٱلذَّارِيَات", "Ad-Dhariyat", "051-ad-dhariyat.ogg", "Meccan"),
        Surah(52, "ٱلطُّور", "At-Tur", "052-at-tur.ogg", "Meccan"),
        Surah(53, "ٱلنَّجْم", "An-Najm", "053-an-najm.ogg", "Meccan"),
        Surah(54, "ٱلْقَمَر", "Al-Qamar", "054-al-qamar.ogg", "Meccan"),
        Surah(55, "ٱلرَّحْمَٰن", "Ar-Rahman", "055-ar-rahman.ogg", "Medinan"),
        Surah(56, "ٱلْوَاقِعَة", "Al-Waqiah", "056-al-waqiah.ogg", "Meccan"),
        Surah(57, "ٱلْحَدِيد", "Al-Hadid", "057-al-hadid.ogg", "Medinan"),
        Surah(58, "ٱلْمُجَادَلَة", "Al-Mujadilah", "058-al-mujadilah.ogg", "Medinan"),
        Surah(59, "ٱلْحَشْر", "Al-Hashr", "059-al-hashr.ogg", "Medinan"),
        Surah(60, "ٱلْمُمْتَحَنَة", "Al-Mumtahanah", "060-al-mumtahanah.ogg", "Medinan"),
        Surah(61, "ٱلصَّفّ", "As-Saff", "061-as-saff.ogg", "Medinan"),
        Surah(62, "ٱلْجُمُعَة", "Al-Jumuah", "062-al-jumuah.ogg", "Medinan"),
        Surah(63, "ٱلْمُنَافِقُون", "Al-Munafiqun", "063-al-munafiqun.ogg", "Medinan"),
        Surah(64, "ٱلتَّغَابُن", "At-Taghabun", "064-at-taghabun.ogg", "Medinan"),
        Surah(65, "ٱلطَّلَاق", "At-Talaq", "065-at-talaq.ogg", "Medinan"),
        Surah(66, "ٱلتَّحْرِيم", "At-Tahrim", "066-at-tahrim.ogg", "Medinan"),
        Surah(67, "ٱلْمُلْك", "Al-Mulk", "067-al-mulk.ogg", "Meccan"),
        Surah(68, "ٱلْقَلَم", "Al-Qalam", "068-al-qalam.ogg", "Meccan"),
        Surah(69, "ٱلْحَاقَّة", "Al-Haqqah", "069-al-haqqah.ogg", "Meccan"),
        Surah(70, "ٱلْمَعَارِج", "Al-Maarij", "070-al-maarij.ogg", "Meccan"),
        Surah(71, "نُوح", "Nuh", "071-nuh.ogg", "Meccan"),
        Surah(72, "ٱلْجِنّ", "Al-Jinn", "072-al-jinn.ogg", "Meccan"),
        Surah(73, "ٱلْمُزَّمِّل", "Al-Muzzammil", "073-al-muzzammil.ogg", "Meccan"),
        Surah(74, "ٱلْمُدَّثِّر", "Al-Muddathir", "074-al-muddathir.ogg", "Meccan"),
        Surah(75, "ٱلْقِيَامَة", "Al-Qiyamah", "075-al-qiyamah.ogg", "Meccan"),
        Surah(76, "ٱلْإِنسَان", "Al-Insan", "076-al-insan.ogg", "Medinan"),
        Surah(77, "ٱلْمُرْسَلَات", "Al-Mursalat", "077-al-mursalat.ogg", "Meccan"),
        Surah(78, "ٱلنَّبَإ", "An-Naba", "078-an-naba.ogg", "Meccan"),
        Surah(79, "ٱلنَّازِعَات", "An-Naziat", "079-an-naziat.ogg", "Meccan"),
        Surah(80, "عَبَس", "Abasa", "080-abasa.ogg", "Meccan"),
        Surah(81, "ٱلتَّكْوِير", "At-Takwir", "081-at-takwir.ogg", "Meccan"),
        Surah(82, "ٱلْإِنفِطَار", "Al-Infitar", "082-al-infitar.ogg", "Meccan"),
        Surah(83, "ٱلْمُطَفِّفِين", "Al-Mutaffifin", "083-al-mutaffifin.ogg", "Meccan"),
        Surah(84, "ٱلْإِنشِقَاق", "Al-Inshiqaq", "084-al-inshiqaq.ogg", "Meccan"),
        Surah(85, "ٱلْبُرُوج", "Al-Buruj", "085-al-buruj.ogg", "Meccan"),
        Surah(86, "ٱلطَّارِق", "At-Tariq", "086-at-tariq.ogg", "Meccan"),
        Surah(87, "ٱلْأَعْلَىٰ", "Al-Ala", "087-al-ala.ogg", "Meccan"),
        Surah(88, "ٱلْغَاشِيَة", "Al-Ghashiyah", "088-al-ghashiyah.ogg", "Meccan"),
        Surah(89, "ٱلْفَجْر", "Al-Fajr", "089-al-fajr.ogg", "Meccan"),
        Surah(90, "ٱلْبَلَد", "Al-Balad", "090-al-balad.ogg", "Meccan"),
        Surah(91, "ٱلشَّمْس", "Ash-Shams", "091-ash-shams.ogg", "Meccan"),
        Surah(92, "ٱلَّيْل", "Al-Lail", "092-al-lail.ogg", "Meccan"),
        Surah(93, "ٱلضُّحَىٰ", "Ad-Duha", "093-ad-duha.ogg", "Meccan"),
        Surah(94, "ٱلشَّرْح", "Ash-Sharh", "094-ash-sharh.ogg", "Meccan"),
        Surah(95, "ٱلتِّين", "At-Tin", "095-at-tin.ogg", "Meccan"),
        Surah(96, "ٱلْعَلَق", "Al-Alaq", "096-al-alaq.ogg", "Meccan"),
        Surah(97, "ٱلْقَدْر", "Al-Qadr", "097-al-qadr.ogg", "Meccan"),
        Surah(98, "ٱلْبَيِّنَة", "Al-Bayyinah", "098-al-bayyinah.ogg", "Medinan"),
        Surah(99, "ٱلزَّلْزَلَة", "Az-Zalzalah", "099-az-zalzalah.ogg", "Medinan"),
        Surah(100, "ٱلْعَادِيَات", "Al-Adiyat", "100-al-adiyat.ogg", "Meccan"),
        Surah(101, "ٱلْقَارِعَة", "Al-Qariah", "101-al-qariah.ogg", "Meccan"),
        Surah(102, "ٱلتَّكَاثُر", "At-Takathur", "102-at-takathur.ogg", "Meccan"),
        Surah(103, "ٱلْعَصْر", "Al-Asr", "103-al-asr.ogg", "Meccan"),
        Surah(104, "ٱلْهُمَزَة", "Al-Humazah", "104-al-humazah.ogg", "Meccan"),
        Surah(105, "ٱلْفِيل", "Al-Fil", "105-al-fil.ogg", "Meccan"),
        Surah(106, "قُرَيْش", "Quraish", "106-quraish.ogg", "Meccan"),
        Surah(107, "ٱلْمَاعُون", "Al-Maun", "107-al-maun.ogg", "Meccan"),
        Surah(108, "ٱلْكَوْثَر", "Al-Kawthar", "108-al-kawthar.ogg", "Meccan"),
        Surah(109, "ٱلْكَافِرُون", "Al-Kafirun", "109-al-kafirun.ogg", "Meccan"),
        Surah(110, "ٱلنَّصْر", "An-Nasr", "110-an-nasr.ogg", "Medinan"),
        Surah(111, "ٱلْمَسَد", "Al-Masad", "111-al-masad.ogg", "Meccan"),
        Surah(112, "ٱلْإِخْلَاص", "Al-Ikhlas", "112-al-ikhlas.ogg", "Meccan"),
        Surah(113, "ٱلْفَلَق", "Al-Falaq", "113-al-falaq.ogg", "Meccan"),
        Surah(114, "ٱلنَّاس", "An-Nas", "114-an-nas.ogg", "Meccan")
    )
}
