/*
 * Copyright 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.starception.submission.prayer.model

/**
 * A country's entry from `country_prayer_methods.json`, as written.
 *
 * The raw method and madhhab names are kept rather than pre-resolved to enums so
 * the mapping stays visible in [prayerDefaultsFor] instead of being baked into
 * generated data — several of these names have no dedicated method and fall back,
 * and that is worth being able to read.
 */
data class CountryEntry(
    val countryName: String,
    val methodName: String,
    val madhhabName: String,
    /** Per-prayer minute adjustments; only a few countries carry any. */
    val timeOffsets: Map<String, Int> = emptyMap(),
)

/**
 * Generated from `app/src/main/assets/country_prayer_methods.json` — the same
 * data Android reads, as Kotlin so it needs no asset loading or JSON parsing and
 * works identically on both platforms.
 *
 * Regenerate rather than hand-edit if the JSON changes.
 */
internal val COUNTRY_ENTRIES: Map<String, CountryEntry> = mapOf(
    "AD" to CountryEntry("Andorra", "Europe", "Hanafi", emptyMap()),
    "AE" to CountryEntry("United Arab Emirates", "UAE_IACAD", "Shafi", mapOf("fajr" to 0, "sunrise" to -3, "dhuhr" to 3, "asr" to 3, "maghrib" to 3, "isha" to 0)),
    "AF" to CountryEntry("Afghanistan", "University_of_Karachi", "Hanafi", emptyMap()),
    "AG" to CountryEntry("Antigua and Barbuda", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "AI" to CountryEntry("Anguilla", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "AL" to CountryEntry("Albania", "Europe", "Hanafi", emptyMap()),
    "AM" to CountryEntry("Armenia", "Europe", "Hanafi", emptyMap()),
    "AO" to CountryEntry("Angola", "South_Africa", "Shafi", emptyMap()),
    "AQ" to CountryEntry("Antarctica", "Australia", "Hanafi", emptyMap()),
    "AR" to CountryEntry("Argentina", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "AS" to CountryEntry("American Samoa", "Australia", "Hanafi", emptyMap()),
    "AT" to CountryEntry("Austria", "Europe", "Hanafi", emptyMap()),
    "AU" to CountryEntry("Australia", "Australia", "Hanafi", emptyMap()),
    "AW" to CountryEntry("Aruba", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "AX" to CountryEntry("Åland Islands", "Europe", "Hanafi", emptyMap()),
    "AZ" to CountryEntry("Azerbaijan", "University_of_Karachi", "Jafari", emptyMap()),
    "BA" to CountryEntry("Bosnia and Herzegovina", "Europe", "Hanafi", emptyMap()),
    "BB" to CountryEntry("Barbados", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BD" to CountryEntry("Bangladesh", "University_of_Karachi", "Hanafi", emptyMap()),
    "BE" to CountryEntry("Belgium", "Europe", "Hanafi", emptyMap()),
    "BF" to CountryEntry("Burkina Faso", "Morocco", "Maliki", emptyMap()),
    "BG" to CountryEntry("Bulgaria", "Europe", "Hanafi", emptyMap()),
    "BH" to CountryEntry("Bahrain", "Umm_al_Qura_University_Makkah", "Maliki", emptyMap()),
    "BI" to CountryEntry("Burundi", "Egypt", "Shafi", emptyMap()),
    "BJ" to CountryEntry("Benin", "Egypt", "Maliki", emptyMap()),
    "BL" to CountryEntry("Saint Barthélemy", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BM" to CountryEntry("Bermuda", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BN" to CountryEntry("Brunei", "Brunei", "Shafi", emptyMap()),
    "BO" to CountryEntry("Bolivia", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BQ" to CountryEntry("Bonaire, Sint Eustatius and Saba", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BR" to CountryEntry("Brazil", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BS" to CountryEntry("Bahamas", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "BT" to CountryEntry("Bhutan", "University_of_Karachi", "Hanafi", emptyMap()),
    "BV" to CountryEntry("Bouvet Island", "South_Africa", "Hanafi", emptyMap()),
    "BW" to CountryEntry("Botswana", "South_Africa", "Shafi", emptyMap()),
    "BY" to CountryEntry("Belarus", "Europe", "Hanafi", emptyMap()),
    "BZ" to CountryEntry("Belize", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CA" to CountryEntry("Canada", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CC" to CountryEntry("Cocos (Keeling) Islands", "Australia", "Shafi", emptyMap()),
    "CD" to CountryEntry("Congo (Democratic Republic)", "Egypt", "Maliki", emptyMap()),
    "CF" to CountryEntry("Central African Republic", "Egypt", "Maliki", emptyMap()),
    "CG" to CountryEntry("Congo (Republic)", "Egypt", "Maliki", emptyMap()),
    "CH" to CountryEntry("Switzerland", "Europe", "Hanafi", emptyMap()),
    "CI" to CountryEntry("Côte d'Ivoire", "Morocco", "Maliki", emptyMap()),
    "CK" to CountryEntry("Cook Islands", "Australia", "Hanafi", emptyMap()),
    "CL" to CountryEntry("Chile", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CM" to CountryEntry("Cameroon", "Egypt", "Maliki", emptyMap()),
    "CN" to CountryEntry("China", "University_of_Karachi", "Hanafi", emptyMap()),
    "CO" to CountryEntry("Colombia", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CR" to CountryEntry("Costa Rica", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CU" to CountryEntry("Cuba", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CV" to CountryEntry("Cape Verde", "Morocco", "Maliki", emptyMap()),
    "CW" to CountryEntry("Curaçao", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "CX" to CountryEntry("Christmas Island", "Australia", "Shafi", emptyMap()),
    "CY" to CountryEntry("Cyprus", "Europe", "Hanafi", emptyMap()),
    "CZ" to CountryEntry("Czech Republic", "Europe", "Hanafi", emptyMap()),
    "DE" to CountryEntry("Germany", "Germany_Turkish_Islamic_Union", "Hanafi", emptyMap()),
    "DJ" to CountryEntry("Djibouti", "Egypt", "Shafi", emptyMap()),
    "DK" to CountryEntry("Denmark", "Europe", "Hanafi", emptyMap()),
    "DM" to CountryEntry("Dominica", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "DO" to CountryEntry("Dominican Republic", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "DZ" to CountryEntry("Algeria", "Algeria", "Maliki", emptyMap()),
    "EC" to CountryEntry("Ecuador", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "EE" to CountryEntry("Estonia", "Europe", "Hanafi", emptyMap()),
    "EG" to CountryEntry("Egypt", "Egyptian_General_Authority_of_Survey", "Shafi", emptyMap()),
    "EH" to CountryEntry("Western Sahara", "Morocco", "Maliki", emptyMap()),
    "ER" to CountryEntry("Eritrea", "Egypt", "Shafi", emptyMap()),
    "ES" to CountryEntry("Spain", "Europe", "Maliki", emptyMap()),
    "ET" to CountryEntry("Ethiopia", "Egypt", "Shafi", emptyMap()),
    "FI" to CountryEntry("Finland", "Europe", "Hanafi", emptyMap()),
    "FJ" to CountryEntry("Fiji", "Australia", "Hanafi", emptyMap()),
    "FK" to CountryEntry("Falkland Islands", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "FM" to CountryEntry("Micronesia", "Australia", "Hanafi", emptyMap()),
    "FO" to CountryEntry("Faroe Islands", "Europe", "Hanafi", emptyMap()),
    "FR" to CountryEntry("France", "France_Union_of_Islamic_Organizations", "Maliki", emptyMap()),
    "GA" to CountryEntry("Gabon", "Egypt", "Maliki", emptyMap()),
    "GB" to CountryEntry("United Kingdom", "London_Unified_Islamic_Society", "Hanafi", emptyMap()),
    "GD" to CountryEntry("Grenada", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "GE" to CountryEntry("Georgia", "Europe", "Hanafi", emptyMap()),
    "GF" to CountryEntry("French Guiana", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "GG" to CountryEntry("Guernsey", "Europe", "Hanafi", emptyMap()),
    "GH" to CountryEntry("Ghana", "Egypt", "Maliki", emptyMap()),
    "GI" to CountryEntry("Gibraltar", "Europe", "Maliki", emptyMap()),
    "GL" to CountryEntry("Greenland", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "GM" to CountryEntry("Gambia", "Morocco", "Maliki", emptyMap()),
    "GN" to CountryEntry("Guinea", "Morocco", "Maliki", emptyMap()),
    "GP" to CountryEntry("Guadeloupe", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "GQ" to CountryEntry("Equatorial Guinea", "Egypt", "Maliki", emptyMap()),
    "GR" to CountryEntry("Greece", "Europe", "Hanafi", emptyMap()),
    "GS" to CountryEntry("South Georgia and South Sandwich Islands", "South_Africa", "Hanafi", emptyMap()),
    "GT" to CountryEntry("Guatemala", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "GU" to CountryEntry("Guam", "Australia", "Hanafi", emptyMap()),
    "GW" to CountryEntry("Guinea-Bissau", "Morocco", "Maliki", emptyMap()),
    "GY" to CountryEntry("Guyana", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "HK" to CountryEntry("Hong Kong", "University_of_Karachi", "Hanafi", emptyMap()),
    "HM" to CountryEntry("Heard Island and McDonald Islands", "Australia", "Hanafi", emptyMap()),
    "HN" to CountryEntry("Honduras", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "HR" to CountryEntry("Croatia", "Europe", "Hanafi", emptyMap()),
    "HT" to CountryEntry("Haiti", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "HU" to CountryEntry("Hungary", "Europe", "Hanafi", emptyMap()),
    "ID" to CountryEntry("Indonesia", "Indonesia", "Shafi", emptyMap()),
    "IE" to CountryEntry("Ireland", "Europe", "Hanafi", emptyMap()),
    "IL" to CountryEntry("Israel", "Umm_al_Qura_University_Makkah", "Hanafi", emptyMap()),
    "IM" to CountryEntry("Isle of Man", "Europe", "Hanafi", emptyMap()),
    "IN" to CountryEntry("India", "University_of_Karachi", "Hanafi", emptyMap()),
    "IO" to CountryEntry("British Indian Ocean Territory", "University_of_Karachi", "Shafi", emptyMap()),
    "IQ" to CountryEntry("Iraq", "Umm_al_Qura_University_Makkah", "Jafari", emptyMap()),
    "IR" to CountryEntry("Iran", "Institute_of_Geophysics_University_of_Tehran", "Jafari", emptyMap()),
    "IS" to CountryEntry("Iceland", "Europe", "Hanafi", emptyMap()),
    "IT" to CountryEntry("Italy", "Europe", "Hanafi", emptyMap()),
    "JE" to CountryEntry("Jersey", "Europe", "Hanafi", emptyMap()),
    "JM" to CountryEntry("Jamaica", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "JO" to CountryEntry("Jordan", "Umm_al_Qura_University_Makkah", "Hanafi", emptyMap()),
    "JP" to CountryEntry("Japan", "University_of_Karachi", "Hanafi", emptyMap()),
    "KE" to CountryEntry("Kenya", "Egypt", "Shafi", emptyMap()),
    "KG" to CountryEntry("Kyrgyzstan", "University_of_Karachi", "Hanafi", emptyMap()),
    "KH" to CountryEntry("Cambodia", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "KI" to CountryEntry("Kiribati", "Australia", "Hanafi", emptyMap()),
    "KM" to CountryEntry("Comoros", "Egypt", "Shafi", emptyMap()),
    "KN" to CountryEntry("Saint Kitts and Nevis", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "KP" to CountryEntry("North Korea", "University_of_Karachi", "Hanafi", emptyMap()),
    "KR" to CountryEntry("South Korea", "University_of_Karachi", "Hanafi", emptyMap()),
    "KW" to CountryEntry("Kuwait", "Kuwait", "Maliki", emptyMap()),
    "KY" to CountryEntry("Cayman Islands", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "KZ" to CountryEntry("Kazakhstan", "University_of_Karachi", "Hanafi", emptyMap()),
    "LA" to CountryEntry("Laos", "Department_of_Islamic_Advancement_Malaysia", "Hanafi", emptyMap()),
    "LB" to CountryEntry("Lebanon", "Umm_al_Qura_University_Makkah", "Shafi", emptyMap()),
    "LC" to CountryEntry("Saint Lucia", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "LI" to CountryEntry("Liechtenstein", "Europe", "Hanafi", emptyMap()),
    "LK" to CountryEntry("Sri Lanka", "University_of_Karachi", "Shafi", emptyMap()),
    "LR" to CountryEntry("Liberia", "Morocco", "Maliki", emptyMap()),
    "LS" to CountryEntry("Lesotho", "South_Africa", "Shafi", emptyMap()),
    "LT" to CountryEntry("Lithuania", "Europe", "Hanafi", emptyMap()),
    "LU" to CountryEntry("Luxembourg", "Europe", "Hanafi", emptyMap()),
    "LV" to CountryEntry("Latvia", "Europe", "Hanafi", emptyMap()),
    "LY" to CountryEntry("Libya", "Egypt", "Maliki", emptyMap()),
    "MA" to CountryEntry("Morocco", "Morocco", "Maliki", emptyMap()),
    "MC" to CountryEntry("Monaco", "Europe", "Hanafi", emptyMap()),
    "MD" to CountryEntry("Moldova", "Europe", "Hanafi", emptyMap()),
    "ME" to CountryEntry("Montenegro", "Europe", "Hanafi", emptyMap()),
    "MF" to CountryEntry("Saint Martin (French part)", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "MG" to CountryEntry("Madagascar", "South_Africa", "Shafi", emptyMap()),
    "MH" to CountryEntry("Marshall Islands", "Australia", "Hanafi", emptyMap()),
    "MK" to CountryEntry("North Macedonia", "Europe", "Hanafi", emptyMap()),
    "ML" to CountryEntry("Mali", "Morocco", "Maliki", emptyMap()),
    "MM" to CountryEntry("Myanmar", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "MN" to CountryEntry("Mongolia", "University_of_Karachi", "Hanafi", emptyMap()),
    "MO" to CountryEntry("Macao", "University_of_Karachi", "Hanafi", emptyMap()),
    "MP" to CountryEntry("Northern Mariana Islands", "Australia", "Hanafi", emptyMap()),
    "MQ" to CountryEntry("Martinique", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "MR" to CountryEntry("Mauritania", "Morocco", "Maliki", emptyMap()),
    "MS" to CountryEntry("Montserrat", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "MT" to CountryEntry("Malta", "Europe", "Hanafi", emptyMap()),
    "MU" to CountryEntry("Mauritius", "South_Africa", "Shafi", emptyMap()),
    "MV" to CountryEntry("Maldives", "Maldives", "Shafi", emptyMap()),
    "MW" to CountryEntry("Malawi", "South_Africa", "Shafi", emptyMap()),
    "MX" to CountryEntry("Mexico", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "MY" to CountryEntry("Malaysia", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "MZ" to CountryEntry("Mozambique", "South_Africa", "Shafi", emptyMap()),
    "NA" to CountryEntry("Namibia", "South_Africa", "Shafi", emptyMap()),
    "NC" to CountryEntry("New Caledonia", "Australia", "Hanafi", emptyMap()),
    "NE" to CountryEntry("Niger", "Morocco", "Maliki", emptyMap()),
    "NF" to CountryEntry("Norfolk Island", "Australia", "Hanafi", emptyMap()),
    "NG" to CountryEntry("Nigeria", "Egypt", "Maliki", emptyMap()),
    "NI" to CountryEntry("Nicaragua", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "NL" to CountryEntry("Netherlands", "Europe", "Hanafi", emptyMap()),
    "NO" to CountryEntry("Norway", "Europe", "Hanafi", emptyMap()),
    "NP" to CountryEntry("Nepal", "University_of_Karachi", "Hanafi", emptyMap()),
    "NR" to CountryEntry("Nauru", "Australia", "Hanafi", emptyMap()),
    "NU" to CountryEntry("Niue", "Australia", "Hanafi", emptyMap()),
    "NZ" to CountryEntry("New Zealand", "Australia", "Hanafi", emptyMap()),
    "OM" to CountryEntry("Oman", "Umm_al_Qura_University_Makkah", "Ibadi", emptyMap()),
    "PA" to CountryEntry("Panama", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "PE" to CountryEntry("Peru", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "PF" to CountryEntry("French Polynesia", "Australia", "Hanafi", emptyMap()),
    "PG" to CountryEntry("Papua New Guinea", "Australia", "Shafi", emptyMap()),
    "PH" to CountryEntry("Philippines", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "PK" to CountryEntry("Pakistan", "University_of_Karachi", "Hanafi", emptyMap()),
    "PL" to CountryEntry("Poland", "Europe", "Hanafi", emptyMap()),
    "PM" to CountryEntry("Saint Pierre and Miquelon", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "PN" to CountryEntry("Pitcairn", "Australia", "Hanafi", emptyMap()),
    "PR" to CountryEntry("Puerto Rico", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "PS" to CountryEntry("Palestine", "Umm_al_Qura_University_Makkah", "Hanafi", emptyMap()),
    "PT" to CountryEntry("Portugal", "Europe", "Maliki", emptyMap()),
    "PW" to CountryEntry("Palau", "Australia", "Hanafi", emptyMap()),
    "PY" to CountryEntry("Paraguay", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "QA" to CountryEntry("Qatar", "Qatar", "Hanbali", emptyMap()),
    "RE" to CountryEntry("Réunion", "South_Africa", "Shafi", emptyMap()),
    "RO" to CountryEntry("Romania", "Europe", "Hanafi", emptyMap()),
    "RS" to CountryEntry("Serbia", "Europe", "Hanafi", emptyMap()),
    "RU" to CountryEntry("Russia", "Russia", "Hanafi", emptyMap()),
    "RW" to CountryEntry("Rwanda", "Egypt", "Shafi", emptyMap()),
    "SA" to CountryEntry("Saudi Arabia", "Umm_al_Qura_University_Makkah", "Hanbali", emptyMap()),
    "SB" to CountryEntry("Solomon Islands", "Australia", "Shafi", emptyMap()),
    "SC" to CountryEntry("Seychelles", "South_Africa", "Shafi", emptyMap()),
    "SD" to CountryEntry("Sudan", "Egypt", "Maliki", emptyMap()),
    "SE" to CountryEntry("Sweden", "Europe", "Hanafi", emptyMap()),
    "SG" to CountryEntry("Singapore", "Singapore", "Shafi", emptyMap()),
    "SH" to CountryEntry("Saint Helena, Ascension and Tristan da Cunha", "South_Africa", "Hanafi", emptyMap()),
    "SI" to CountryEntry("Slovenia", "Europe", "Hanafi", emptyMap()),
    "SJ" to CountryEntry("Svalbard and Jan Mayen", "Europe", "Hanafi", emptyMap()),
    "SK" to CountryEntry("Slovakia", "Europe", "Hanafi", emptyMap()),
    "SL" to CountryEntry("Sierra Leone", "Morocco", "Maliki", emptyMap()),
    "SM" to CountryEntry("San Marino", "Europe", "Hanafi", emptyMap()),
    "SN" to CountryEntry("Senegal", "Morocco", "Maliki", emptyMap()),
    "SO" to CountryEntry("Somalia", "Egypt", "Shafi", emptyMap()),
    "SR" to CountryEntry("Suriname", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "SS" to CountryEntry("South Sudan", "Egypt", "Maliki", emptyMap()),
    "ST" to CountryEntry("São Tomé and Príncipe", "Egypt", "Maliki", emptyMap()),
    "SV" to CountryEntry("El Salvador", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "SX" to CountryEntry("Sint Maarten (Dutch part)", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "SY" to CountryEntry("Syria", "Umm_al_Qura_University_Makkah", "Hanafi", emptyMap()),
    "SZ" to CountryEntry("Eswatini", "South_Africa", "Shafi", emptyMap()),
    "TC" to CountryEntry("Turks and Caicos Islands", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "TD" to CountryEntry("Chad", "Egypt", "Maliki", emptyMap()),
    "TF" to CountryEntry("French Southern Territories", "South_Africa", "Hanafi", emptyMap()),
    "TG" to CountryEntry("Togo", "Egypt", "Maliki", emptyMap()),
    "TH" to CountryEntry("Thailand", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "TJ" to CountryEntry("Tajikistan", "University_of_Karachi", "Hanafi", emptyMap()),
    "TK" to CountryEntry("Tokelau", "Australia", "Hanafi", emptyMap()),
    "TL" to CountryEntry("Timor-Leste", "Indonesia", "Shafi", emptyMap()),
    "TM" to CountryEntry("Turkmenistan", "University_of_Karachi", "Hanafi", emptyMap()),
    "TN" to CountryEntry("Tunisia", "Tunisia", "Maliki", emptyMap()),
    "TO" to CountryEntry("Tonga", "Australia", "Hanafi", emptyMap()),
    "TR" to CountryEntry("Turkey", "Turkey", "Hanafi", emptyMap()),
    "TT" to CountryEntry("Trinidad and Tobago", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "TV" to CountryEntry("Tuvalu", "Australia", "Hanafi", emptyMap()),
    "TW" to CountryEntry("Taiwan", "University_of_Karachi", "Hanafi", emptyMap()),
    "TZ" to CountryEntry("Tanzania", "Egypt", "Shafi", emptyMap()),
    "UA" to CountryEntry("Ukraine", "Europe", "Hanafi", emptyMap()),
    "UG" to CountryEntry("Uganda", "Egypt", "Shafi", emptyMap()),
    "UM" to CountryEntry("United States Minor Outlying Islands", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "US" to CountryEntry("United States", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "UY" to CountryEntry("Uruguay", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "UZ" to CountryEntry("Uzbekistan", "University_of_Karachi", "Hanafi", emptyMap()),
    "VA" to CountryEntry("Vatican City", "Europe", "Hanafi", emptyMap()),
    "VC" to CountryEntry("Saint Vincent and the Grenadines", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "VE" to CountryEntry("Venezuela", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "VG" to CountryEntry("Virgin Islands (British)", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "VI" to CountryEntry("Virgin Islands (U.S.)", "Islamic_Society_of_North_America", "Hanafi", emptyMap()),
    "VN" to CountryEntry("Vietnam", "Department_of_Islamic_Advancement_Malaysia", "Shafi", emptyMap()),
    "VU" to CountryEntry("Vanuatu", "Australia", "Shafi", emptyMap()),
    "WF" to CountryEntry("Wallis and Futuna", "Australia", "Hanafi", emptyMap()),
    "WS" to CountryEntry("Samoa", "Australia", "Hanafi", emptyMap()),
    "XK" to CountryEntry("Kosovo", "Europe", "Hanafi", emptyMap()),
    "YE" to CountryEntry("Yemen", "Umm_al_Qura_University_Makkah", "Shafi", emptyMap()),
    "YT" to CountryEntry("Mayotte", "South_Africa", "Shafi", emptyMap()),
    "ZA" to CountryEntry("South Africa", "South_Africa", "Shafi", emptyMap()),
    "ZM" to CountryEntry("Zambia", "South_Africa", "Shafi", emptyMap()),
    "ZW" to CountryEntry("Zimbabwe", "South_Africa", "Shafi", emptyMap()),
)
