package com.starception.submission.prayer.model

import java.time.LocalTime

/**
 * Represents an AI-suggested offset for a specific prayer time.
 *
 * This is generated by comparing our calculated prayer time with a reference
 * source (Aladhan API) to help users set accurate offsets.
 */
data class PrayerTimeSuggestion(
    val prayerName: String,
    val suggestedOffset: Int,       // Suggested offset in minutes
    val currentOffset: Int,          // User's current offset
    val ourCalculatedTime: LocalTime,
    val referenceTime: LocalTime,
    val differenceMinutes: Int       // referenceTime - ourCalculatedTime
) {
    /**
     * Returns true if the suggestion differs from current user offset.
     * Only show alternating animation when there's a meaningful difference.
     */
    fun hasDifferentSuggestion(): Boolean {
        return suggestedOffset != currentOffset
    }

    /**
     * Returns the suggested offset as a formatted string with sparkle.
     * e.g., "✨+3m" or "✨-2m" or "✨0m"
     */
    fun getFormattedSuggestion(): String {
        return when {
            suggestedOffset > 0 -> "✨+${suggestedOffset}m"
            suggestedOffset < 0 -> "✨${suggestedOffset}m"
            else -> "✨0m"
        }
    }

    /**
     * Returns the current offset as a formatted string.
     * e.g., "+5m" or "-2m" or "0m"
     */
    fun getFormattedCurrentOffset(): String {
        return when {
            currentOffset > 0 -> "+${currentOffset}m"
            currentOffset < 0 -> "${currentOffset}m"
            else -> "0m"
        }
    }
}

/**
 * Container for all prayer time suggestions for a day.
 */
data class DayPrayerSuggestions(
    val fajr: PrayerTimeSuggestion?,
    val dhuhr: PrayerTimeSuggestion?,
    val asr: PrayerTimeSuggestion?,
    val maghrib: PrayerTimeSuggestion?,
    val isha: PrayerTimeSuggestion?,
    val isLoading: Boolean = false,
    val error: String? = null
) {
    companion object {
        val EMPTY = DayPrayerSuggestions(
            fajr = null,
            dhuhr = null,
            asr = null,
            maghrib = null,
            isha = null
        )

        val LOADING = DayPrayerSuggestions(
            fajr = null,
            dhuhr = null,
            asr = null,
            maghrib = null,
            isha = null,
            isLoading = true
        )
    }

    /**
     * Gets suggestion for a specific prayer by name.
     */
    fun getSuggestionFor(prayerName: String): PrayerTimeSuggestion? {
        return when (prayerName.lowercase()) {
            "fajr" -> fajr
            "dhuhr" -> dhuhr
            "asr" -> asr
            "maghrib" -> maghrib
            "isha" -> isha
            else -> null
        }
    }

    /**
     * Returns true if any prayer has a suggestion that differs from current offset.
     */
    fun hasAnySuggestion(): Boolean {
        return listOfNotNull(fajr, dhuhr, asr, maghrib, isha)
            .any { it.hasDifferentSuggestion() }
    }
}
